In [40]:
# Loading the dataset
import pandas as pd
dataset = pd.read_excel("age_salary.xlsx")
dataset

age   salary
0   25.0  35000.0
1   27.0  40000.0
2   50.0  54000.0
3   35.0      NaN
4   40.0  60000.0
5   35.0  58000.0
6    NaN  52000.0
7   48.0  79000.0
8   50.0  83000.0
9   37.0      NaN
10  21.0  24000.0
11   NaN  60000.0
12  63.0  70000.0

In [46]:
# Classifying the dependent and Independent Variables
# X = dataset.iloc[:,a:b].values (in case of multiple independent variables)
X = dataset.iloc[:,:-1].values # Takes all rows of all columns except the last column
Y = dataset.iloc[:,-1].values # Takes all rows of the last column
Y

array([35000., 40000., 54000.,    nan, 60000., 58000., 52000., 79000.,
       83000.,    nan, 24000., 60000., 70000.])

In [49]:
# Dealing with Missing Data
import numpy as np
from sklearn.impute import SimpleImputer
imp = SimpleImputer(missing_values=np.nan, strategy="mean")
X = imp.fit_transform(X)
Y = Y.reshape(-1,1)
Y = imp.fit_transform(Y)
Y = Y.reshape(-1)
Y

array([35000.        , 40000.        , 54000.        , 55909.09090909,
       60000.        , 58000.        , 52000.        , 79000.        ,
       83000.        , 55909.09090909, 24000.        , 60000.        ,
       70000.        ])

In [50]:
# Dealing with Categorical Data
dataset = pd.read_excel("dataset.xlsx")
dataset

nation purchased_item   age   salary
0     India             No  25.0  35000.0
1    Russia            Yes  27.0  40000.0
2   Germany             No  50.0  54000.0
3    Russia            Yes  35.0  55909.1
4   Germany            Yes  40.0  60000.0
5     India             No  35.0  58000.0
6    Russia            Yes  39.1  52000.0
7     India             No  48.0  79000.0
8   Germany            Yes  50.0  83000.0
9     India             No  37.0  55909.1
10  Germany            Yes  21.0  24000.0
11    India             No  39.1  60000.0
12   Russia            Yes  63.0  70000.0

In [59]:
# Dealing with Categorical Data
X = dataset.iloc[:, [0,2,3]].values
Y = dataset.iloc[:, 1].values
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
le_X = LabelEncoder()
X[:, 0] = le_X.fit_transform(X[:,0])
ohe_X = OneHotEncoder()
X = ohe_X.fit_transform(X).toarray()
X

array([[0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
        0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
        0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 1., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
        0., 0., 0., 0., 

In [60]:
Y = le_X.fit_transform(Y)
Y

array([0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1])

In [68]:
# Splitting the Dataset into Training and Testing sets
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 3, random_state = 0)

In [70]:
# Scaling the features
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

sc_Y = StandardScaler()
Y_train = Y_train.reshape(len(Y_train), 1)
Y_train = sc_Y.fit_transform(Y_train)
Y_train = Y_train.ravel()
Y_train

array([ 1., -1.,  1.,  1., -1., -1.,  1., -1., -1.,  1.])